# Generated by Django 4.0.3 on 2022-10-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_automobile_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvo',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
